STRONG_HINT_PATTERNS = [
    r"\badmin panel\b",
    r"\badmin dashboard\b",
    r"\bweb admin\b",
    r"\bcustomer app\b",
    r"\bclient app\b",
    r"\bdriver app\b",
    r"\bdelivery app\b",
    r"\bvendor portal\b",
    r"\bcustomer portal\b",
    r"\bbackend api\b",
    r"\bmobile application\b",
    r"\bcustomer web\b",
    r"\bweb portal\b",
    r"لوحة تحكم",
    r"لوحة تحكم إدارية",
    r"تطبيق العميل",
    r"تطبيق عميل",
    r"تطبيق السائق",
    r"تطبيق مندوب",
    r"بوابة المورد",
    r"بوابة العملاء",
    r"واجهة برمجية",
]

POSSIBLE_HINT_PATTERNS = [
    r"\bapp\b",
    r"\bapps\b",
    r"\bmobile\b",
    r"\bportal\b",
    r"\bdashboard\b",
    r"\bwebsite\b",
    r"\bweb\b",
    r"\bapi\b",
    r"\bpanel\b",
    r"تطبيق",
    r"ابلكيشن",
    r"موبايل",
    r"بوابة",
    r"موقع",
    r"لوحة",
]
